name: "AI Commit Summary"
description: "Generate commit-by-commit summaries for pull requests using OpenAI"

author: "Shiva Sharma"

inputs:
  github_token:
    description: "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"
    required: true

  inputs:
  huggingface_api_key:
    required: true

  model:
    description: "OpenAI model to use"
    required: false
    default: "gpt-4o-mini"

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: "git-commit"
  color: "blue"
