name: AI Commit Summary

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: read
  issues: write
  contents: read

jobs:
  summarize:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run AI Commit Summary
        uses: shiva1631/ai-commit-summary-action@test4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
